# TODO: Make sure to swap out all these env variables. Use some type of secret manager

services:
  backend:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - ./tmp:/tmp
    env_file: .env
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    command: ["./waller", "api"]

  # Worker Process 
  worker:
    build: .
    volumes:
      - ./tmp:/tmp
    env_file: .env
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    command: ["./waller", "worker"]

  db:
    image: postgres:14-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=wallpapers_db
    healthcheck: 
      test: ["CMD-SHELL", "pg_isready -U user -d wallpapers_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
